#
# Makefile.annotlib
# Autoconf Fragment when using annotations
# Jose Kahan, Sep 1999
#

AMAYA_ANNOT_SRC= ../annotlib/libAnnot.a 

ANNOT_SCHEMAS= annot_schemas

annot_force :

amaya_annot_schemas : annot_force
	@(cd ../annotlib ; $(MAKE) libAnnotSchemas)

amaya_comp_annot :  ../annotlib/libAnnot.a
../annotlib/libAnnot.a : amaya_annot_schemas annot_force
	@(cd ../annotlib ; $(MAKE) libAnnot)





