/* File generated by app - do not edit! */
/* #################################### */
/* Types and attributes for the document type Topics */

/* Global attributes */
#define Topics_ATTR_Language 1

/* Local attributes */
#define Topics_ATTR_XmlBody 2
#define Topics_ATTR_XmlBody_VAL_Yes_ 1
#define Topics_ATTR_Charset 3
#define Topics_ATTR_Model_HREF_ 4
#define Topics_ATTR_Closed_ 5
#define Topics_ATTR_Closed__VAL_Yes 1
#define Topics_ATTR_Open_ 6
#define Topics_ATTR_Open__VAL_Yes_ 1
#define Topics_ATTR_Selected_ 7
#define Topics_ATTR_Selected__VAL_Yes_ 1
#define Topics_ATTR_HREF_ 8

/* Basic elements */
#define Topics_EL_TEXT_UNIT 1
#define Topics_EL_GRAPHICS_UNIT 2
#define Topics_EL_SYMBOL_UNIT 3
#define Topics_EL_PICTURE_UNIT 4
#define Topics_EL_PAGE_BREAK 6
#define Topics_EL_ANY_TYPE 7

/* Elements */
#define Topics_EL_Document 8
#define Topics_EL_C_Empty 9
#define Topics_EL_Topics 10
#define Topics_EL_Topic_item 11
#define Topics_EL_Topic_title 12
#define Topics_EL_Topic_content 13
#define Topics_EL_Item 14
#define Topics_EL_Bookmark_item 15
#define Topics_EL_Bookmark_title 16
#define Topics_EL_Separator_item 17
#define Topics_EL_SeeAlso_content 18
#define Topics_EL_SeeAlso_item 19
#define Topics_EL_SeeAlso_title 20
