.TH AMAYA 1 "March 2001" "Debian Project"
.SH NAME
amaya \- WYSIWYG HTML editor
.SH SYNOPSIS
.B amaya
[ -display host ] [ document ]

.SH "DESCRIPTION"
.B amaya
is a WYSIWYG HTML editor from w3.org. It also doubles a web browser.
.PP
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.SH SEE ALSO
A more complete documentation in HTML of Amaya is available in the
/usr/share/doc/amaya/WX directory.
.SH OPTIONS
.TP
.B \-display host
Defines the remote X-Window host screen where Amaya should display Web pages,
provided this feature is available.
.SH AUTHOR
This manual page was written by Steve Dunham <dunham@debian.org> and updated
by Regis Boudin <regis@boudin.name>.
