.TH AMAYA 1 "March 2001" "Debian Project"
.SH NAME
amaya \- WYSIWYG HTML editor
.SH SYNOPSIS
.B amaya
[file]

.SH "DESCRIPTION"
.B amaya
is a WYWIWYG HTML editor from w3.org.   It also doubles a web browser.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page, and Debian
requires one.
.SH SEE ALSO
 For a pointer to documentation on how to use amaya, run
the program with no arguments.
.SH OPTIONS
The only argument this program takes is the name of a HTML file
to load.
.SH AUTHOR
This manual page was written by Steve Dunham <dunham@debian.org>.
