.TH AMAYA 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
amaya \- WYSIWYG HTML editor
.SH SYNOPSIS
.B amaya
.I "[file]"

.SH "DESCRIPTION"

.B amaya
is a WYWIWYG HTML editor from w3.org.   It also doubles a web browser.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page, and Debian
requires one. For a pointer to documentation on how to use amaya, run
the program with no arguments.
.SH OPTIONS
The only argument this program takes is the name of a HTML file
to load.

.SH AUTHOR
This manual page was written by Steve Dunham <dunham@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
