Document: amaya
Title: Debian amaya Manual
Author: <insert document author here>
Abstract: This manual describes what amaya is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amaya/amaya.sgml.gz

Format: postscript
Files: /usr/share/doc/amaya/amaya.ps.gz

Format: text
Files: /usr/share/doc/amaya/amaya.text.gz

Format: HTML
Index: /usr/share/doc/amaya/html/index.html
Files: /usr/share/doc/amaya/html/*.html

  
